server:
  port: 80

spring:
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: itheima
    pub-sub-domain: true
  rabbitmq:
    host: localhost
    port: 5672

rocketmq:
  name-server: localhost:9876
  producer:
    group: group_rocketmq