# 2、配置相关信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: 12345678

#设置MP相关的配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_